assignment06:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"

#      type: mysql
#      server: "{{ env_var('DBT_ENV_SECRET_MYSQL_HOST') }}"
#      port: "{{ env_var('DBT_ENV_SECRET_MYSQL_USER_MYSQL_PORT') | int }}"
#      schema: "{{ env_var('DBT_ENV_SECRET_MYSQL_SCHEMA') }}"
#      username: "{{ env_var('DBT_ENV_SECRET_MYSQL_USER') }}"
#      password: "{{ env_var('DBT_ENV_SECRET_MYSQL_PASSWORD') }}"
#      ssl_disabled: False
