


# mount the dbt directory as a volume
services:
  scheduler:
#    environment:
#      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=False
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT=/usr/local/airflow/certs/server.crt
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY=/usr/local/airflow/certs/private.key

#      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=443  # Ensure webserver is using HTTPS port
#      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=False
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT=/usr/local/airflow/certs/server.crt
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY=/usr/local/airflow/certs/private.key
#      - GUNICORN_CMD_ARGS="--ssl-version=5 --ciphers=TLSv1.2"
    volumes:
      - ./data:/usr/local/airflow/data
      - ./csv:/usr/local/airflow/csv
#      - ./certs:/usr/local/airflow/certs  # Mount the certificate directory
#      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
#    ports:
#      - "443:8080"  # Expose HTTPS port 443