# mount the dbt directory as a volume
services:
  scheduler:
#    environment:
#      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=False
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT=/usr/local/airflow/certs/server.crt
#      - AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY=/usr/local/airflow/certs/private.key

#      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=False

    volumes:
      - ./data:/usr/local/airflow/data
      - ./csv:/usr/local/airflow/csv
      - ./csv_extracted:/usr/local/airflow/csv_extracted
      - ./csv_processed:/usr/local/airflow/csv_processed
#      - ./certs:/usr/local/airflow/certs  # Mount the certificate directory
#      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
